JSON_AS_ASCII = False

HOSTNAME = 'hadoop102'
PORT = '3306'
DATABASE = 'db1'
USERNAME = 'root'
PASSWORD = '111111'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = "1234567891111"

MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = "6698381@qqq.com"
MAIL_PASSWORD = "123456"
MAIL_DEFAULT_SENDER = "6698381@qqq.com"