# Generated by Django 4.0.4 on 2022-05-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_account_userinfo_create_time_userinfo_dpart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='account',
        ),
    ]
