"""empty message

Revision ID: 728dfea01e60
Revises: 
Create Date: 2022-05-07 21:33:39.158601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '728dfea01e60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_index('idx_users_deleted_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(fsp=3), nullable=True),
    sa.Column('username', mysql.LONGTEXT(), nullable=True),
    sa.Column('password', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
